apiVersion: v1
kind: Pod
metadata:
  name: vkubelet-boc
spec:
  containers:
  - name: vkubelet-boc
    image: jayden21/virtual-kubelet:v2.1.3
    # "IfNotPresent" is used to prevent Minikube from trying to pull from the registry (and failing) in the first place.
    imagePullPolicy: IfNotPresent
    args:
    - /virtual-kubelet
    - --nodename
    - vkubelet-boc
    - --provider
    - mock
    - --provider-config
    - /vkubelet-boc-cfg.json
    - --startup-timeout
    - 10s
    - --klog.v
    - "2"
    - --klog.logtostderr
    - --log-level
    - debug
    env:
    - name: KUBELET_PORT
      value: "10250"
    - name: VKUBELET_POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    ports:
    - name: metrics
      containerPort: 10255
    readinessProbe:
      httpGet:
        path: /stats/summary
        port: metrics
  serviceAccountName: virtual-kubelet
